# Use this notbook for your 3 choices of APIs

In [14]:
import json
import requests
import pandas as pd
from pandas import json_normalize

# 1) Dungeons and Dragons:

In [15]:
response = requests.get('https://www.dnd5eapi.co/api/classes/wizard')
#https://api.open5e.com/?format=json
results = response.json()
results

{'index': 'wizard',
 'name': 'Wizard',
 'hit_die': 6,
 'proficiency_choices': [{'desc': 'Choose two from Arcana, History, Insight, Investigation, Medicine, and Religion',
   'choose': 2,
   'type': 'proficiencies',
   'from': {'option_set_type': 'options_array',
    'options': [{'option_type': 'reference',
      'item': {'index': 'skill-arcana',
       'name': 'Skill: Arcana',
       'url': '/api/proficiencies/skill-arcana'}},
     {'option_type': 'reference',
      'item': {'index': 'skill-history',
       'name': 'Skill: History',
       'url': '/api/proficiencies/skill-history'}},
     {'option_type': 'reference',
      'item': {'index': 'skill-insight',
       'name': 'Skill: Insight',
       'url': '/api/proficiencies/skill-insight'}},
     {'option_type': 'reference',
      'item': {'index': 'skill-investigation',
       'name': 'Skill: Investigation',
       'url': '/api/proficiencies/skill-investigation'}},
     {'option_type': 'reference',
      'item': {'index': 'skill-medicine',
       'name': 'Skill: Medicine',
       'url': '/api/proficiencies/skill-medicine'}},
     {'option_type': 'reference',
      'item': {'index': 'skill-religion',
       'name': 'Skill: Religion',
       'url': '/api/proficiencies/skill-religion'}}]}}],
 'proficiencies': [{'index': 'daggers',
   'name': 'Daggers',
   'url': '/api/proficiencies/daggers'},
  {'index': 'darts', 'name': 'Darts', 'url': '/api/proficiencies/darts'},
  {'index': 'slings', 'name': 'Slings', 'url': '/api/proficiencies/slings'},
  {'index': 'quarterstaffs',
   'name': 'Quarterstaffs',
   'url': '/api/proficiencies/quarterstaffs'},
  {'index': 'crossbows-light',
   'name': 'Crossbows, light',
   'url': '/api/proficiencies/crossbows-light'},
  {'index': 'saving-throw-int',
   'name': 'Saving Throw: INT',
   'url': '/api/proficiencies/saving-throw-int'},
  {'index': 'saving-throw-wis',
   'name': 'Saving Throw: WIS',
   'url': '/api/proficiencies/saving-throw-wis'}],
 'saving_throws': [{'index': 'int',
   'name': 'INT',
   'url': '/api/ability-scores/int'},
  {'index': 'wis', 'name': 'WIS', 'url': '/api/ability-scores/wis'}],
 'starting_equipment': [{'equipment': {'index': 'spellbook',
    'name': 'Spellbook',
    'url': '/api/equipment/spellbook'},
   'quantity': 1}],
 'starting_equipment_options': [{'desc': '(a) a quarterstaff or (b) a dagger',
   'choose': 1,
   'type': 'equipment',
   'from': {'option_set_type': 'options_array',
    'options': [{'option_type': 'counted_reference',
      'count': 1,
      'of': {'index': 'quarterstaff',
       'name': 'Quarterstaff',
       'url': '/api/equipment/quarterstaff'}},
     {'option_type': 'counted_reference',
      'count': 1,
      'of': {'index': 'dagger',
       'name': 'Dagger',
       'url': '/api/equipment/dagger'}}]}},
  {'desc': '(a) a component pouch or (b) an arcane focus',
   'choose': 1,
   'type': 'equipment',
   'from': {'option_set_type': 'options_array',
    'options': [{'option_type': 'counted_reference',
      'count': 1,
      'of': {'index': 'component-pouch',
       'name': 'Component pouch',
       'url': '/api/equipment/component-pouch'}},
     {'option_type': 'choice',
      'choice': {'desc': 'arcane focus',
       'choose': 1,
       'type': 'equipment',
       'from': {'option_set_type': 'equipment_category',
        'equipment_category': {'index': 'arcane-foci',
         'name': 'Arcane Foci',
         'url': '/api/equipment-categories/arcane-foci'}}}}]}},
  {'desc': '(a) a scholar’s pack or (b) an explorer’s pack',
   'choose': 1,
   'type': 'equipment',
   'from': {'option_set_type': 'options_array',
    'options': [{'option_type': 'counted_reference',
      'count': 1,
      'of': {'index': 'scholars-pack',
       'name': "Scholar's Pack",
       'url': '/api/equipment/scholars-pack'}},
     {'option_type': 'counted_reference',
      'count': 1,
      'of': {'index': 'explorers-pack',
       'name': "Explorer's Pack",
       'url': '/api/equipment/explorers-pack'}}]}}],
 'class_levels': '/api/classes/wizard/levels',
 'multi_classing': {'prerequisites': [{'ability_score': {'index': 'int',
     'name': 'INT',
     'url': '/api/ability-scores/int'},
    'minimum_score': 13}],
  'proficiencies': []},
 'subclasses': [{'index': 'evocation',
   'name': 'Evocation',
   'url': '/api/subclasses/evocation'}],
 'spellcasting': {'level': 1,
  'spellcasting_ability': {'index': 'int',
   'name': 'INT',
   'url': '/api/ability-scores/int'},
  'info': [{'name': 'Cantrips',
    'desc': ['At 1st level, you know three cantrips of your choice from the wizard spell list. You learn additional wizard cantrips of your choice at higher levels, as shown in the Cantrips Known column of the Wizard table.']},
   {'name': 'Spellbook',
    'desc': ['At 1st level, you have a spellbook containing six 1st- level wizard spells of your choice. Your spellbook is the repository of the wizard spells you know, except your cantrips, which are fixed in your mind.']},
   {'name': 'Preparing and Casting Spells',
    'desc': ["The Wizard table shows how many spell slots you have to cast your spells of 1st level and higher. To cast one of these spells, you must expend a slot of the spell's level or higher. You regain all expended spell slots when you finish a long rest.",
     'You prepare the list of wizard spells that are available for you to cast. To do so, choose a number of wizard spells from your spellbook equal to your Intelligence modifier + your wizard level (minimum of one spell). The spells must be of a level for which you have spell slots.',
     "For example, if you're a 3rd-level wizard, you have four 1st-level and two 2nd-level spell slots. With an Intelligence of 16, your list of prepared spells can include six spells of 1st or 2nd level, in any combination, chosen from your spellbook. If you prepare the 1st-level spell magic missile, you can cast it using a 1st-level or a 2nd-level slot. Casting the spell doesn't remove it from your list of prepared spells.",
     'You can change your list of prepared spells when you finish a long rest. Preparing a new list of wizard spells requires time spent studying your spellbook and memorizing the incantations and gestures you must make to cast the spell: at least 1 minute per spell level for each spell on your list.']},
   {'name': 'Spellcasting Ability',
    'desc': ['Intelligence is your spellcasting ability for your wizard spells, since you learn your spells through dedicated study and memorization. You use your Intelligence whenever a spell refers to your spellcasting ability. In addition, you use your Intelligence modifier when setting the saving throw DC for a wizard spell you cast and when making an attack roll with one.',
     'Spell save DC = 8 + your proficiency bonus + your Intelligence modifier.',
     'Spell attack modifier = your proficiency bonus + your Intelligence modifier.']},
   {'name': 'Ritual Casting',
    'desc': ["You can cast a wizard spell as a ritual if that spell has the ritual tag and you have the spell in your spellbook. You don't need to have the spell prepared."]},
   {'name': 'Spellcasting Focus',
    'desc': ['You can use an arcane focus as a spellcasting focus for your wizard spells.']}]},
 'spells': '/api/classes/wizard/spells',
 'url': '/api/classes/wizard'}

In [16]:
dnd = pd.json_normalize(results)
dnd

,index,name,hit_die,proficiency_choices,proficiencies,saving_throws,starting_equipment,starting_equipment_options,class_levels,subclasses,spells,url,multi_classing.prerequisites,multi_classing.proficiencies,spellcasting.level,spellcasting.spellcasting_ability.index,spellcasting.spellcasting_ability.name,spellcasting.spellcasting_ability.url,spellcasting.info
0,wizard,Wizard,6,"[{'desc': 'Choose two from Arcana, History, In...","[{'index': 'daggers', 'name': 'Daggers', 'url'...","[{'index': 'int', 'name': 'INT', 'url': '/api/...","[{'equipment': {'index': 'spellbook', 'name': ...",[{'desc': '(a) a quarterstaff or (b) a dagger'...,/api/classes/wizard/levels,"[{'index': 'evocation', 'name': 'Evocation', '...",/api/classes/wizard/spells,/api/classes/wizard,"[{'ability_score': {'index': 'int', 'name': 'I...",[],1,int,INT,/api/ability-scores/int,"[{'name': 'Cantrips', 'desc': ['At 1st level, ..."

In [17]:
#data.proficiency_choices[0]

In [18]:
# df = pd.DataFrame()

# for d in dnd:
#     df_tmp = pd.json_normalize(results)
#     row = pd.DataFrame(df_tmp.to_numpy().flatten()).T.dropna(axis=1)
#     row.columns = df_tmp.columns
#     df = pd.concat([df, row])

# display(df.reset_index(drop=True))

In [19]:
dnd_pr_ch = dnd.proficiency_choices[0]
dnd_pr_ch_norm = pd.json_normalize(dnd_pr_ch)
dnd_pr_ch_norm

,desc,choose,type,from.option_set_type,from.options
0,"Choose two from Arcana, History, Insight, Inve...",2,proficiencies,options_array,"[{'option_type': 'reference', 'item': {'index'..."

In [20]:
dnd_pr_ch_norm2 = dnd_pr_ch_norm['from.options'][0]
dnd_pr_ch_norm3 = pd.json_normalize(dnd_pr_ch_norm2)
dnd_pr_ch_norm3

,option_type,item.index,item.name,item.url
0,reference,skill-arcana,Skill: Arcana,/api/proficiencies/skill-arcana
1,reference,skill-history,Skill: History,/api/proficiencies/skill-history
2,reference,skill-insight,Skill: Insight,/api/proficiencies/skill-insight
3,reference,skill-investigation,Skill: Investigation,/api/proficiencies/skill-investigation
4,reference,skill-medicine,Skill: Medicine,/api/proficiencies/skill-medicine
5,reference,skill-religion,Skill: Religion,/api/proficiencies/skill-religion

In [43]:
dnd_pr = dnd.proficiencies[0]
dnd_pr_norm = pd.json_normalize(dnd_pr)
dnd_pr_norm = dnd_pr_norm.drop(['index'], axis = 1)
display(dnd_pr_norm.reset_index(drop=True))

                name                                  url
0            Daggers           /api/proficiencies/daggers
1              Darts             /api/proficiencies/darts
2             Slings            /api/proficiencies/slings
3      Quarterstaffs     /api/proficiencies/quarterstaffs
4   Crossbows, light   /api/proficiencies/crossbows-light
5  Saving Throw: INT  /api/proficiencies/saving-throw-int
6  Saving Throw: WIS  /api/proficiencies/saving-throw-wis

In [100]:
# complicated... parking

In [50]:
# df = pd.concat([dnd, dnd_pr_ch_norm3])
# df = df.drop(['index'], axis = 1)
# display(df.reset_index(drop=True))

In [54]:
# pd.concat([dnd_pr_ch_norm3, dnd_pr_norm], axis=0)

,option_type,item.index,item.name,item.url,name,url
0,reference,skill-arcana,Skill: Arcana,/api/proficiencies/skill-arcana,NaN,NaN
1,reference,skill-history,Skill: History,/api/proficiencies/skill-history,NaN,NaN
2,reference,skill-insight,Skill: Insight,/api/proficiencies/skill-insight,NaN,NaN
3,reference,skill-investigation,Skill: Investigation,/api/proficiencies/skill-investigation,NaN,NaN
4,reference,skill-medicine,Skill: Medicine,/api/proficiencies/skill-medicine,NaN,NaN
5,reference,skill-religion,Skill: Religion,/api/proficiencies/skill-religion,NaN,NaN
0,NaN,NaN,NaN,NaN,Daggers,/api/proficiencies/daggers
1,NaN,NaN,NaN,NaN,Darts,/api/proficiencies/darts
2,NaN,NaN,NaN,NaN,Slings,/api/proficiencies/slings
3,NaN,NaN,NaN,NaN,Quarterstaffs,/api/proficiencies/quarterstaffs
4,NaN,NaN,NaN,NaN,"Crossbows, light",/api/proficiencies/crossbows-light
5,NaN,NaN,NaN,NaN,Saving Throw: INT,/api/proficiencies/saving-throw-int
6,NaN,NaN,NaN,NaN,Saving Throw: WIS,/api/proficiencies/saving-throw-wis

# Magic the Gathering:

In [56]:
response = requests.get('http://api.magicthegathering.io/v1/cards?page=311')

data = pd.DataFrame(response.json())
data

                                                cards
0   {'name': 'Spoils of Evil', 'manaCost': '{2}{B}...
1   {'name': 'Spoils of War', 'manaCost': '{X}{B}'...
2   {'name': 'Stench of Evil', 'manaCost': '{2}{B}...
3   {'name': 'Stromgald Cabal', 'manaCost': '{1}{B...
4   {'name': 'Touch of Death', 'manaCost': '{2}{B}...
..                                                ...
95  {'name': 'Pyknite', 'manaCost': '{2}{G}', 'cmc...
96  {'name': 'Regeneration', 'manaCost': '{1}{G}',...
97  {'name': 'Rime Dryad', 'manaCost': '{G}', 'cmc...
98  {'name': 'Ritual of Subdual', 'manaCost': '{4}...
99  {'name': 'Scaled Wurm', 'manaCost': '{7}{G}', ...

[100 rows x 1 columns]

In [63]:
# data.cards[0]

In [76]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', None)
cards = pd.json_normalize(data.cards)
cards = cards.drop(['foreignNames', 'legalities'], axis = 1)
cards.head(1)

,name,manaCost,cmc,colors,colorIdentity,type,types,rarity,set,setName,text,flavor,artist,number,layout,multiverseid,imageUrl,rulings,printings,originalText,originalType,id,subtypes,power,toughness,supertypes
0,Spoils of Evil,{2}{B},3.0,[B],[B],Instant,[Instant],Rare,ICE,Ice Age,"For each artifact or creature card in target opponent's graveyard, add {C} and you gain 1 life.","""Virtue has its rewards, as does its opposite.""\n—Lim-Dûl, the Necromancer",Quinton Hoover,163,normal,2487,http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=2487&type=card,"[{'date': '2004-10-04', 'text': 'The text “for each artifact or creature” means the sum of cards which are either creature and/or artifact. Artifact creatures are not double counted.'}]",[ICE],"For each artifact or creature in target opponent's graveyard, add one colorless mana to your mana pool and gain 1 life.",Interrupt,c3027065-4403-5577-993c-921961b76e6a,NaN,NaN,NaN,NaN

In [53]:
# data.cards[0]

#... also parking

# Carbon Footprint of Websites (eg. IronHack)

In [38]:
response = requests.get('https://api.websitecarbon.com/site?url=https%3A%2F%2Fwww.ironhack.com%2F')

results = response.json()
results

{'url': 'https://www.ironhack.com/',
 'green': True,
 'bytes': 1537910,
 'cleanerThan': 0.63,
 'statistics': {'adjustedBytes': 1161122.05,
  'energy': 0.00087591713340953,
  'co2': {'grid': {'grams': 0.38715537296701225,
    'litres': 0.21533581844425217},
   'renewable': {'grams': 0.33565144552253195,
    'litres': 0.18668933399963222}}},
 'timestamp': 1680007660}

In [39]:
flattened_data = json_normalize(results)
flattened_data

,url,green,bytes,cleanerThan,timestamp,statistics.adjustedBytes,statistics.energy,statistics.co2.grid.grams,statistics.co2.grid.litres,statistics.co2.renewable.grams,statistics.co2.renewable.litres
0,https://www.ironhack.com/,True,1537910,0.63,1680007660,1161122.05,0.000876,0.387155,0.215336,0.335651,0.186689

# Emojis:

In [46]:
response = requests.get('https://emojihub.yurace.pro/api/all')
results = response.json()
#results

In [47]:
flattened_data = json_normalize(results)
flattened_data

,name,category,group,htmlCode,unicode
0,grinning face,smileys and people,face positive,[&#128512;],[U+1F600]
1,grinning face with smiling eyes,smileys and people,face positive,[&#128513;],[U+1F601]
2,face with tears of joy,smileys and people,face positive,[&#128514;],[U+1F602]
3,rolling on the floor laughing,smileys and people,face positive,[&#129315;],[U+1F923]
4,smiling face with open mouth,smileys and people,face positive,[&#128515;],[U+1F603]
...,...,...,...,...,...
1786,yemen,flags,flags,"[&#127486;, &#127466;]","[U+1F1FE, U+1F1EA]"
1787,mayotte,flags,flags,"[&#127486;, &#127481;]","[U+1F1FE, U+1F1F9]"
1788,south africa,flags,flags,"[&#127487;, &#127462;]","[U+1F1FF, U+1F1E6]"
1789,zambia,flags,flags,"[&#127487;, &#127474;]","[U+1F1FF, U+1F1F2]"
1790,zimbabwe,flags,flags,"[&#127487;, &#127484;]","[U+1F1FF, U+1F1FC]"

# Bible verses

In [49]:
response = requests.get('https://bible-api.com/romans 12:1-2,5-7,9,13:1-9&10')
results = response.json()
# results

In [51]:
flattened_data = json_normalize(results)
flattened_data.T

                                                                  0
reference                             Romans 12:1-2,5-7,9,13:1-9,10
verses            [{'book_id': 'ROM', 'book_name': 'Romans', 'ch...
text              Therefore I urge you, brothers, by the mercies...
translation_id                                                  web
translation_name                                World English Bible
translation_note                                      Public Domain

In [52]:
verses = flattened_data.verses[0]
verses_norm = pd.json_normalize(verses)
verses_norm

,book_id,book_name,chapter,verse,text
0,ROM,Romans,12,1,"Therefore I urge you, brothers, by the mercies..."
1,ROM,Romans,12,2,"Don’t be conformed to this world, but be trans..."
2,ROM,Romans,12,5,"so we, who are many, are one body in Christ, a..."
3,ROM,Romans,12,6,Having gifts differing according to the grace ...
4,ROM,Romans,12,7,"or service, let us give ourselves to service; ..."
5,ROM,Romans,12,9,Let love be without hypocrisy. Abhor that whic...
6,ROM,Romans,13,1,Let every soul be in subjection to the higher ...
7,ROM,Romans,13,2,"Therefore he who resists the authority, withst..."
8,ROM,Romans,13,3,"For rulers are not a terror to the good work, ..."
9,ROM,Romans,13,4,for he is a servant of God to you for good. Bu...
10,ROM,Romans,13,5,"Therefore you need to be in subjection, not on..."
11,ROM,Romans,13,6,"For this reason you also pay taxes, for they a..."
12,ROM,Romans,13,7,Therefore give everyone what you owe: if you o...
13,ROM,Romans,13,8,"Owe no one anything, except to love one anothe..."
14,ROM,Romans,13,9,"For the commandments, “You shall not commit ad..."
15,ROM,Romans,13,10,Love doesn’t harm a neighbor. Love therefore i...